### ISSUE TITLE
Нет домашнего задания

### ISSUE THREAD

**Issue by marina-cyber** [alexvilno/PSU_TIMESERIES#1]
Нет блокнотов с дз.  
Уже середина ноября, и 7 домашних заданий позади. И впереди - несколько дз + проект.
Не загоняйте себя в безвыходную ситуацию.
Слейте второстепенные бранчи в main.

**Comment by alexvilno** [comment]
**Виноват!** _Все будет сделано в лучшем виде не позднее 25.11.2023 23:59 (GMT+5)_
