### ISSUE TITLE
Задание 4

### ISSUE THREAD

**Issue by QQQiwi** [alexvilno/PSU_TIMESERIES#5]
На самом деле здорово что ты делаешь задачи через пул реквесты, мне этот подход очень приятен. Но в целом в этом необходимости нет, можешь просто добавлять решенные задания сразу в основную ветку. Но если хочешь продолжить делать через PR, тогда я буду считать, что задание готово к сдаче при начилии пул реквеста с ним.

**Comment by alexvilno** [comment]
Да, я буду PR кидать. Я там ещё сделал HW2, но случайно смерджил а мейн его, так что HW2 тоже готово
